<a href="https://colab.research.google.com/github/Noemigb2001-09/ai2023-2NoemiG/blob/main/Copia_NumPy_Exercises_for_Data_Analysis(11_12_2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [2]:
# Import numpy as np and see the version
# your code here
import numpy as np
print("Versión de NumPy:", np.__version__)

pass

Versión de NumPy: 1.23.5


In [3]:
# Create a 1D array of numbers from 0 to 9
# your code here
my_array = np.arange(10)
print(my_array)

pass

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Create random vector of size 10 and replace the maximum value by 0
#your code here
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
print("Original random vector:")
print(random_vector)
pass

Original random vector:
[0.45425669 0.66673344 0.13955995 0.04895211 0.44881431 0.74633769
 0.86274656 0.         0.19065935 0.8423107 ]


In [5]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
indices = np.where(arr == 8)
print("Indices of the number 8:", indices)
if len(indices[0]) > 0:
    row_index, col_index = indices
    print("Number 8 is at position:", (row_index[0], col_index[0]))
    print("Value at position (row, col):", arr[row_index[0], col_index[0]])
else:
    print("Number 8 not found in the array.")
pass

Indices of the number 8: (array([1]), array([2]))
Number 8 is at position: (1, 2)
Value at position (row, col): 8


In [6]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr = np.array([1, 2, 3, 4, 5, 6, 7])
subset = arr[2:5]
print("Numbers [3, 4, 5]:", subset)
pass

Numbers [3, 4, 5]: [3 4 5]


In [7]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr = np.array([1, 2, 3, 4, 5, 6, 7])
last_four = arr[-4:]
print("Last 4 numbers:", last_four)
pass

Last 4 numbers: [4 5 6 7]


In [8]:
# Create a 3×3 numpy array of all True’s
# your code here
true_array = np.full((3, 3), True)
print(true_array)
pass

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
# Extract all odd numbers from arr
# your code here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 != 0]
print("Odd numbers:", odd_numbers)
pass

Odd numbers: [1 3 5 7 9]


In [10]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
my_vector = np.arange(10, 50)
print(my_vector)
pass


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
# Reverse a vector (first element becomes last)
my_vector = np.array([1, 2, 3, 4, 5])
reversed_vector = my_vector[::-1]
print("Original vector:", my_vector)
print("Reversed vector:", reversed_vector)
pass

Original vector: [1 2 3 4 5]
Reversed vector: [5 4 3 2 1]


In [12]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
random_array = np.random.randint(low=1, high=100, size=(10, 10))

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)
pass

Random Array:
[[94 57 33 86 78 62 27  3 34 29]
 [65 84 89 83  7 23  1 22 42 85]
 [93 84 55 20 13 85 22 96 84 36]
 [64  2 32 92 50 45 92 42 24 39]
 [64 84 75 63 48 94 36 49 53 39]
 [79  3 13 18 47 84 52  5 77 39]
 [20 69 32 59 37 16 98 79 81 83]
 [26 42 84 89 21 88 11 14 83 83]
 [55 97 30  4 98 18  9 87 87 92]
 [43 81 87 82 13 93 42 42 89 36]]

Minimum Value: 1
Maximum Value: 98


In [13]:
# Create a 3x3x3 array with random values
random_3d_array = np.random.rand(3, 3, 3)
print(random_3d_array)
pass

[[[0.33261895 0.20180614 0.51743728]
  [0.39801968 0.17827009 0.95647891]
  [0.38501734 0.62047411 0.96784906]]

 [[0.64157745 0.6598531  0.9875205 ]
  [0.30545589 0.04021362 0.9194049 ]
  [0.03936327 0.30166815 0.71853083]]

 [[0.26070349 0.66296491 0.43775645]
  [0.31130861 0.19831581 0.04279157]
  [0.1995455  0.37978766 0.44125998]]]


In [14]:
# Replace all odd numbers in arr with -1
# your code here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print("Modified array:", arr)
pass

Modified array: [-1  2 -1  4 -1  6 -1  8 -1]


In [15]:
# Create an array of type float
float_array = np.array([1.0, 2.5, 3.7, 4.2, 5.9])
print("Float Array:", float_array)
print("Data Type:", float_array.dtype)
pass

Float Array: [1.  2.5 3.7 4.2 5.9]
Data Type: float64


In [16]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
my_1d_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
my_2d_array = my_1d_array.reshape(2, -1)
print("Original 1D Array:", my_1d_array)
print("Reshaped 2D Array:")
print(my_2d_array)
pass

Original 1D Array: [1 2 3 4 5 6 7 8]
Reshaped 2D Array:
[[1 2 3 4]
 [5 6 7 8]]


In [18]:
# How to find common values between two arrays?

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
common_values = np.intersect1d(Z1, Z2)
print("Array Z1:", Z1)
print("Array Z2:", Z2)
print("Common Values:", common_values)
pass

Array Z1: [3 4 8 3 8 6 5 1 8 0]
Array Z2: [5 6 4 8 5 2 1 5 2 5]
Common Values: [1 4 5 6 8]


In [19]:
#  Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
are_equal = np.array_equal(A, B)
print("Array A:", A)
print("Array B:", B)
print("Arrays are equal:", are_equal)
pass

Array A: [0 1 0 0 0]
Array B: [1 1 1 0 0]
Arrays are equal: False


In [20]:
# Stack arrays a and b vertically
# your code here
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
result = np.vstack((A, B))
print("Array A:", A)
print("Array B:", B)
print("Stacked Result:")
print(result)
pass

Array A: [0 1 1 1 0]
Array B: [0 1 1 1 1]
Stacked Result:
[[0 1 1 1 0]
 [0 1 1 1 1]]


In [21]:
# Stack the arrays a and b horizontally.
# your code here
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
result = np.hstack((A, B))
print("Array A:", A)
print("Array B:", B)
print("Horizontally Stacked Result:", result)
pass

Array A: [0 0 1 1 1]
Array B: [0 1 1 0 0]
Horizontally Stacked Result: [0 0 1 1 1 0 1 1 0 0]


In [23]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
result = tmp[(tmp >= 5) & (tmp <= 10)]
print("Items between 5 and 10:", result)
pass

Items between 5 and 10: [ 5  6  7  8  9 10]


In [26]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
#a = np.array([5, 7, 9, 8, 6, 4, 5])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)



5

In [27]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
pass


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]
random_array = np.random.uniform(5, 10, size=(5, 3))

print(random_array)

[[5.69000243 8.61500302 8.33361564]
 [8.74446911 7.37298826 8.62301823]
 [7.46750432 9.50427543 7.6508673 ]
 [7.06844372 6.99498903 9.27605436]
 [8.87607898 5.64019119 8.50522609]]
