<a href="https://colab.research.google.com/github/Noemigb2001-09/ai2023-2NoemiG/blob/main/Practica4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)
print('multiplicacion numbers')
print(a*b)
print('adding numbers')
print (np.add(a,b))
print('substracting numbers')
print(np.multiply(a,b))
print('divide numbers')
print(np.divide(a,b))

[[10  8 10  6]
 [ 9  1  7  2]
 [ 4  9 10  4]]
[[ 8 10  3  7]
 [ 5  2  6  3]
 [ 6  1  5  4]]
(3, 4)
(3, 4)
adding numbers
[[18 18 13 13]
 [14  3 13  5]
 [10 10 15  8]]
substracting numbers
[[ 2 -2  7 -1]
 [ 4 -1  1 -1]
 [-2  8  5  0]]
multiplicacion numbers
[[80 80 30 42]
 [45  2 42  6]
 [24  9 50 16]]
adding numbers
[[18 18 13 13]
 [14  3 13  5]
 [10 10 15  8]]
substracting numbers
[[80 80 30 42]
 [45  2 42  6]
 [24  9 50 16]]
divide numbers
[[1.25       0.8        3.33333333 0.85714286]
 [1.8        0.5        1.16666667 0.66666667]
 [0.66666667 9.         2.         1.        ]]


In [ ]:
a = np.random.randint(1, 11, size=(2,3))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print("---------------")
print(b)
print("---------------")
print(np.dot(a,b))
print("---------------")
print(a.dot(b))

[[ 1  9 10]
 [ 4  4 10]]
---------------
[[ 3  1  1 10]
 [ 7  2 10  6]
 [ 3  4  1  6]]
---------------
[[ 96  59 101 124]
 [ 70  52  54 124]]
---------------
[[ 96  59 101 124]
 [ 70  52  54 124]]


In [ ]:
a=np.random.randint(1,11, size=(2,2))
print(a.shape)
print("---------------")
print(type(a))
print("---------------")
print(a)
print("---------------")
print(a.T)

(2, 2)
---------------
<class 'numpy.ndarray'>
---------------
[[5 1]
 [2 1]]
---------------
[[5 2]
 [1 1]]


In [ ]:
a=np.random.randint(1,11, size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print("---------------")
print(b.shape)

(4, 3)
---------------
(3,)


In [ ]:
c=np.empty_like(a)
print(a)
print("-------------")
print(b)
print("-------------")
print(c.shape)
print("-------------")
print(c)
print("-----------")

[[ 6  8  9]
 [ 8  3 10]
 [ 8  9  3]
 [ 9  9  5]]
-------------
[1 0 2]
-------------
(4, 3)
-------------
[[10  8 10]
 [ 6  9  1]
 [ 7  2  4]
 [ 9 10  4]]
-----------


In [ ]:
for i in range(4):
  c[i,:]=a[i,:]+b

In [ ]:
print("Matriz 'a':")
print(a)

print("Vector 'b':")
print(b)

print("Matriz 'c' (resultado de la suma):")
print(c)

Matriz 'a':
[[ 6  8  9]
 [ 8  3 10]
 [ 8  9  3]
 [ 9  9  5]]
Vector 'b':
[1 0 2]
Matriz 'c' (resultado de la suma):
[[ 7  8 11]
 [ 9  3 12]
 [ 9  9  5]
 [10  9  7]]


In [ ]:
a=np.array([1,2,3])
print(a)
b = np.tile(a, (6, 1))
print(b)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a=np.random.randint(0,10, size=(6,6))
print(a)
print("-----------")
aux = np.mean(a)
print(aux)
print("-----------")
aux = np.mean(a, axis=1)
print(aux)
print("-----------")
aux = np.mean(a, axis=0)
print(aux)

[[4 8 1 3 0 5]
 [0 2 2 1 9 5]
 [2 6 8 9 4 9]
 [1 6 3 1 4 1]
 [3 3 5 4 3 1]
 [3 2 2 0 3 7]]
-----------
3.611111111111111
-----------
[3.5        3.16666667 6.33333333 2.66666667 3.16666667 2.83333333]
-----------
[2.16666667 4.5        3.5        3.         3.83333333 4.66666667]
