<a href="https://colab.research.google.com/github/Noemigb2001-09/ai2023-2NoemiG/blob/main/Practica3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
aux=np.array([1,2,3,4,5])
print(aux)
print(aux.shape)

aux2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(aux2)
print(aux2.shape)
print(type(aux2))

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
<class 'numpy.ndarray'>


In [ ]:
tmp=np.zeros((4,4))
print(tmp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print("Matriz full valores del mismo numeroi")
tmp=np.full((4,4),5)
print(tmp)

Matriz full valores del mismo numeroi
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
print("Matriz diagonal")
tmp=np.eye(4,4)
print(tmp)

Matriz diagonal
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print("Matriz de 1")
tmp=np.ones((4,4))
print(tmp)

Matriz de 1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print("Numeros randoms")
tmp=10*np.random.random((4,4))
print(tmp)
print(tmp.shape)

Numeros randoms
[[1.50109553 4.21474175 6.33953103 2.55144467]
 [6.38975952 7.25591227 7.68721214 5.74084077]
 [7.35674301 0.77105108 4.49889537 7.20985295]
 [6.59895347 6.57511687 8.91728059 2.79002289]]
(4, 4)


In [ ]:
print(tmp[:2,:2])

[[1.50109553 4.21474175]
 [6.38975952 7.25591227]]


In [ ]:
print(tmp[:2,1:3])

[[4.21474175 6.33953103]
 [7.25591227 7.68721214]]


In [ ]:
print(tmp[3])

[6.59895347 6.57511687 8.91728059 2.79002289]


In [ ]:
print(tmp[2,2])

4.498895367681762


In [ ]:
print("Numeros randoms")
tmp=10*np.random.random((4,4))
print(tmp)
print(tmp.shape)

Numeros randoms
[[2.76402351 9.52199243 0.42695018 6.0077761 ]
 [2.01244941 1.17727933 2.22572896 8.4514175 ]
 [6.93716009 6.85904727 4.23734433 6.73589454]
 [5.16850676 6.73598386 2.55573237 8.16988946]]
(4, 4)


In [ ]:
mask=tmp>5
print(tmp[mask])

[9.52199243 6.0077761  8.4514175  6.93716009 6.85904727 6.73589454
 5.16850676 6.73598386 8.16988946]


In [ ]:
mask=(tmp>=2)&(tmp<=4)
print(tmp[mask])

[2.76402351 2.01244941 2.22572896 2.55573237]


In [ ]:
# Crear un arreglo de 4x4 con valores aleatorios enteros entre 1 y 100
arreglo = np.random.randint(1, 101, size=(4, 4))

print("Arreglo original:")
print(arreglo)

# Crear una máscara booleana para los números pares
mascara_pares = arreglo % 2 == 0

# Aplicar la máscara para seleccionar los números pares
numeros_pares = arreglo[mascara_pares]

print("Números pares:")
print(numeros_pares)

Arreglo original:
[[20 43 23 83]
 [31 55  8 91]
 [27 64 19 67]
 [27  9 48 85]]
Números pares:
[20  8 64 48]
